# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: http://www.jhipster.tech/profiles/
# More information on configuration properties: http://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DBNAME}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate.generate_statistics: false

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias assessment -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: assessment
# ===================================================================
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# keycloak client config properties
# ===================================================================

kc:
  realm: ${KC_REALM:}
  master.realm: ${KC_MASTER_REALM:}
  client.id: ${KC_CLIENT_ID:}
  server.url: ${KC_SERVER_URL:}
  username: ${KC_USERNAME:}
  password: ${KC_PASSWORD:}
  timeout: ${KC_TIMEOUT:}

application:

endpoints:
  enabled: false # disable all endpoints
