spring:
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/${DBNAME:assessments}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL:false}
    username: ${DBUSER:root}
    password: ${DBPASSWORD:}
  flyway:
    password: ${DBPASSWORD:}
    schemas: ${DBNAME:assessments}


kc:
  realm: ${KC_REALM:lin}
  master.realm: ${KC_MASTER_REALM:master}
  client.id: ${KC_CLIENT_ID:admin-cli}
  server.url: ${KC_SERVER_URL:https://dev-apps.tis.nhs.uk/auth/}
  username: ${KC_USERNAME:admin}
  password: ${KC_PASSWORD:vp689ygIM563Tb67971L02FZU}
  timeout: ${KC_TIMEOUT:10000}
