spring:
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/${DBNAME:assessments}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL:false}
    username: ${DBUSER:root}
    password: ${DBPASSWORD:}

flyway:
  password: ${DBPASSWORD:}
  schemas: ${DBNAME:assessments}


kc:
  realm: ${KC_REALM}
  master.realm: ${KC_MASTER_REALM}
  client.id: ${KC_CLIENT_ID}
  server.url: ${KC_SERVER_URL}
  username: ${KC_USERNAME}
  password: ${KC_PASSWORD}
  timeout: ${KC_TIMEOUT:10000}
